name: Pull GitHub Repository Contents and Deploy to Jenkins

on:
  push:
    branches: [main]

jobs:
  pull_repo_and_deploy:
    name: Pull GitHub Repository Contents and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.YUSUFME3 }}
          password: ${{ secrets.YUSUFME3P }}
          repository: yusufme3/dockerhubgithub
          tag_with_ref: true
